### ISSUE TITLE
Ludicrous mode is missing

### ISSUE THREAD

**Issue by Nerfclasher** [PapaJoesSoup/VesselMover#7] opened 2016-08-08 22:13 UTC

**Comment by PapaJoesSoup** [comment] 2016-08-09 01:47
Duplicate of #6

**Closed by PapaJoesSoup** 2016-08-09 01:47 UTC

**Comment by Nerfclasher** [comment] 2016-08-09 03:26
Number #6 issue ludicrous mode is still missing

**Comment by PapaJoesSoup** [comment] 2016-08-09 03:42
Hmm maybe I uploaded the wrong archive...

**Comment by PapaJoesSoup** [comment] 2016-08-09 03:47
Makes no sense though.  Doc tested and confirmed that all 4 settings were there.  Check your installation

**Comment by PapaJoesSoup** [comment] 2016-08-09 03:56
Did you pull from git or spacedock?
